CREATE TABLE `bf_offline_payment_form` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `corp_id` bigint(20) unsigned NOT NULL COMMENT '企业ID',
  `batch_no` varchar(100) NOT NULL COMMENT '批次号',
  `payment_form_no` varchar(100) NOT NULL COMMENT '付款单编号',
  `payment_type` tinyint(4) NOT NULL COMMENT '付款类型,1对公,2对私',
  `apply_type` tinyint(3) unsigned NOT NULL COMMENT '申请类型,1常规业务,2垫付退回,3到款退回,4折扣单',
  `category_parent_id` bigint(20) unsigned NOT NULL COMMENT '业务大类ID',
  `category_parent` varchar(100) NOT NULL COMMENT '冗余业务大类',
  `category_child_id` bigint(20) unsigned NOT NULL COMMENT '业务小类ID',
  `category_child` varchar(100) NOT NULL COMMENT '冗余业务小类',
  `amount` decimal(12,2) NOT NULL COMMENT '请款金额',
  `payer_bank_name` varchar(100) NOT NULL COMMENT '付款银行名称',
  `payer_bank_no` varchar(100) NOT NULL COMMENT '付款银行卡号',
  `payer_bank_ps` varchar(100) NOT NULL COMMENT '支付附言',
  `payee_bank_name` varchar(100) NOT NULL DEFAULT '' COMMENT '收款银行名称',
  `payee_bank_no` varchar(100) NOT NULL DEFAULT '' COMMENT '收款银行卡号',
  `payee_company_id` bigint(20) unsigned DEFAULT NULL COMMENT '收款方公司ID',
  `payee_bank_account_name` varchar(100) NOT NULL DEFAULT '' COMMENT '收款账户名',
  `payee_company_name` varchar(100) DEFAULT NULL COMMENT '收款方公司名称',
  `detail_count` int(11) NOT NULL COMMENT '明细数量',
  `remark` varchar(1000) NOT NULL DEFAULT '' COMMENT '付款单备注',
  `audit_no` varchar(100) NOT NULL DEFAULT '' COMMENT '审批单号',
  `apply_audit_by` varchar(100) NOT NULL DEFAULT '' COMMENT '提交审批人',
  `apply_audit_account` varchar(100) NOT NULL DEFAULT '' COMMENT '提交审批人账号',
  `audit_template_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '审批模版id',
  `audit_terminal` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '审批终端,1系统内审批,2钉钉端审批',
  `audit_state` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '付款审批状态,1待审批,2审批中,3审批通过,4审批被拒绝,5撤销,6作废',
  `audit_time` datetime DEFAULT NULL COMMENT '状态变更时间',
  `audit_remark` varchar(1000) NOT NULL DEFAULT '' COMMENT '审批备注',
  `audit_by` varchar(100) DEFAULT NULL COMMENT '状态变更人',
  `audit_by_account` varchar(100) DEFAULT NULL COMMENT '状态变更人账号',
  `audit_reason` varchar(100) NOT NULL DEFAULT '' COMMENT '变更原因',
  `adjust_enabled` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '是否需要调整,0否,1是',
  `adjust_by_account` varchar(100) NOT NULL DEFAULT '' COMMENT '调整人账号',
  `adjust_by` varchar(100) NOT NULL DEFAULT '' COMMENT '调整人姓名',
  `adjust_suggest` varchar(100) NOT NULL DEFAULT '' COMMENT '调整建议',
  `pay_no` varchar(100) NOT NULL DEFAULT '' COMMENT '最新支付号',
  `pay_remark` varchar(1000) NOT NULL DEFAULT '' COMMENT '最新支付备注',
  `pay_state` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '最新支付状态,1待支付,2支付中,3已支付(部分成功),4已经支付(全部成功),5已支付(全部失败),6未支付被驳回,7支付成功后被退回',
  `paying_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '支付中金额',
  `pay_unback_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '实付(未退回)',
  `pay_back_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '实付(被退回)',
  `pay_remain_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '剩余可支付',
  `pay_negative_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '已负冲金额',
  `pay_canceled_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '已取消金额',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(100) NOT NULL COMMENT '修改人',
  `update_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '修改人名字',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(100) NOT NULL COMMENT '创建人',
  `create_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '创建人名字',
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除状态,0未删除,1已删除',
  `trace_id` varchar(100) NOT NULL COMMENT 'traceId',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `bf_offline_payment_form_corp_id_IDX` (`corp_id`,`audit_no`),
  KEY `bf_offline_order_corp_id_IDX` (`corp_id`,`payment_form_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1408 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='线下业务-付款单';

CREATE TABLE `bf_no_order_advance_payment_form_normal_payment` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `corp_id` bigint(20) unsigned NOT NULL COMMENT '企业ID',
  `payment_form_id` bigint(20) unsigned NOT NULL COMMENT '付款单ID',
  `form_pay_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '付款单支付方式,1普通支付',
  `order_type` tinyint(3) unsigned NOT NULL COMMENT '订单类型,1正常订单',
  `detail_no` varchar(100) NOT NULL DEFAULT '' COMMENT '明细单号',
  `project_id` bigint(20) unsigned NOT NULL COMMENT '项目ID',
  `project_name` varchar(100) NOT NULL COMMENT '项目名称',
  `customer_id` bigint(20) unsigned NOT NULL COMMENT '客户ID',
  `customer_name` varchar(100) NOT NULL COMMENT '客户名称',
  `expenses_parent_id` bigint(20) unsigned NOT NULL COMMENT '费用大类ID',
  `expenses_parent` varchar(100) NOT NULL COMMENT '冗余费用大类名称',
  `expenses_child_id` bigint(20) unsigned NOT NULL COMMENT '费用小类ID',
  `expenses_child` varchar(100) NOT NULL COMMENT '冗余费用小类名称',
  `amount` decimal(12,2) NOT NULL COMMENT '金额',
  `pay_no` varchar(100) NOT NULL DEFAULT '' COMMENT '最新支付号',
  `pay_state` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '最新支付状态,1待支付,2支付中,3已支付(部分成功),4已经支付(全部成功),5已支付(全部失败),6未支付被驳回,7支付成功后被退回,8已取消',
  `pay_time` datetime DEFAULT NULL COMMENT '支付状态时间',
  `pay_state_reason` varchar(1000) NOT NULL DEFAULT '' COMMENT '支付状态原因',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(100) NOT NULL COMMENT '修改人',
  `update_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '修改人名字',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(100) NOT NULL COMMENT '创建人',
  `create_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '创建人名字',
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除状态,0未删除,1已删除',
  `trace_id` varchar(100) NOT NULL COMMENT 'traceId',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `index_corp_id` (`corp_id`),
  KEY `index_payment_form_id` (`payment_form_id`)
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='无订单垫付-付款单-无订单常规请款缴费-明细';

CREATE TABLE `bf_no_order_advance_payment_form_payment_apply` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `corp_id` bigint(20) unsigned NOT NULL COMMENT '企业ID',
  `payment_form_id` bigint(20) unsigned NOT NULL COMMENT '付款单ID',
  `form_pay_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '付款单支付方式,1普通支付',
  `order_type` tinyint(3) unsigned NOT NULL COMMENT '订单类型,1正常订单',
  `detail_no` varchar(100) NOT NULL DEFAULT '' COMMENT '明细单号',
  `project_id` bigint(20) unsigned NOT NULL COMMENT '项目ID',
  `project_name` varchar(100) NOT NULL COMMENT '项目名称',
  `customer_id` bigint(20) unsigned DEFAULT NULL COMMENT '客户ID',
  `customer_name` varchar(100) DEFAULT NULL COMMENT '客户名称',
  `expenses_parent_id` bigint(20) unsigned NOT NULL COMMENT '费用大类ID',
  `expenses_parent` varchar(100) NOT NULL COMMENT '冗余费用大类名称',
  `expenses_child_id` bigint(20) unsigned NOT NULL COMMENT '费用小类ID',
  `expenses_child` varchar(100) NOT NULL COMMENT '冗余费用小类名称',
  `amount` decimal(12,2) NOT NULL COMMENT '金额',
  `pay_no` varchar(100) NOT NULL DEFAULT '' COMMENT '最新支付号',
  `pay_state` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '最新支付状态,1待支付,2支付中,3已支付(部分成功),4已经支付(全部成功),5已支付(全部失败),6未支付被驳回,7支付成功后被退回,8已取消',
  `pay_time` datetime DEFAULT NULL COMMENT '支付状态时间',
  `pay_state_reason` varchar(1000) NOT NULL DEFAULT '' COMMENT '支付状态原因',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(100) NOT NULL COMMENT '修改人',
  `update_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '修改人名字',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(100) NOT NULL COMMENT '创建人',
  `create_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '创建人名字',
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除状态,0未删除,1已删除',
  `trace_id` varchar(100) NOT NULL COMMENT 'traceId',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `index_corp_id` (`corp_id`),
  KEY `index_payment_form_id` (`payment_form_id`)
) ENGINE=InnoDB AUTO_INCREMENT=155 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='无订单垫付-付款单-无订单垫付请款-明细';

CREATE TABLE `bf_no_order_advance_payment_form_write_off` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `corp_id` bigint(20) unsigned NOT NULL COMMENT '企业ID',
  `payment_form_id` bigint(20) unsigned NOT NULL COMMENT '付款单ID',
  `form_pay_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '付款单支付方式,1普通支付',
  `order_type` tinyint(3) unsigned NOT NULL COMMENT '订单类型,1正常订单',
  `detail_no` varchar(100) NOT NULL DEFAULT '' COMMENT '明细单号',
  `project_id` bigint(20) unsigned NOT NULL COMMENT '项目ID',
  `project_name` varchar(100) NOT NULL COMMENT '项目名称',
  `customer_id` bigint(20) unsigned NOT NULL COMMENT '客户ID',
  `customer_name` varchar(100) NOT NULL COMMENT '客户名称',
  `expenses_parent_id` bigint(20) unsigned NOT NULL COMMENT '费用大类ID',
  `expenses_parent` varchar(100) NOT NULL COMMENT '冗余费用大类名称',
  `expenses_child_id` bigint(20) unsigned NOT NULL COMMENT '费用小类ID',
  `expenses_child` varchar(100) NOT NULL COMMENT '冗余费用小类名称',
  `amount` decimal(12,2) NOT NULL COMMENT '金额',
  `pay_no` varchar(100) NOT NULL DEFAULT '' COMMENT '最新支付号',
  `pay_state` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '最新支付状态,1待支付,2支付中,3已支付(部分成功),4已经支付(全部成功),5已支付(全部失败),6未支付被驳回,7支付成功后被退回,8已取消',
  `pay_time` datetime DEFAULT NULL COMMENT '支付状态时间',
  `pay_state_reason` varchar(1000) NOT NULL DEFAULT '' COMMENT '支付状态原因',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(100) NOT NULL COMMENT '修改人',
  `update_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '修改人名字',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(100) NOT NULL COMMENT '创建人',
  `create_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '创建人名字',
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除状态,0未删除,1已删除',
  `trace_id` varchar(100) NOT NULL COMMENT 'traceId',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `index_corp_id` (`corp_id`),
  KEY `index_payment_form_id` (`payment_form_id`)
) ENGINE=InnoDB AUTO_INCREMENT=78 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='无订单垫付-付款单-无订单垫付核销费-明细';

CREATE TABLE `bf_offline_payment_form_advance_back_detail` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `corp_id` bigint(20) unsigned NOT NULL COMMENT '企业ID',
  `payment_form_id` bigint(20) unsigned NOT NULL COMMENT '付款单ID',
  `form_pay_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '付款单支付方式,1普通支付,2被负冲,3负冲',
  `advance_no` varchar(100) NOT NULL COMMENT '垫款单编号',
  `project_id` bigint(20) unsigned NOT NULL COMMENT '项目ID',
  `project_name` varchar(100) NOT NULL COMMENT '项目名称',
  `customer_id` bigint(20) unsigned NOT NULL COMMENT '客户ID',
  `customer_name` varchar(100) NOT NULL COMMENT '客户名称',
  `amount` decimal(12,2) NOT NULL COMMENT '垫款退回金额',
  `pay_no` varchar(100) NOT NULL DEFAULT '' COMMENT '最新支付号',
  `pay_remark` varchar(1000) NOT NULL DEFAULT '' COMMENT '最新支付备注',
  `pay_state` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '最新支付状态,1待支付,2支付中,3已支付(部分成功),4已经支付(全部成功),5已支付(全部失败),6未支付被驳回,7支付成功后被退回',
  `pay_state_reason` varchar(1000) NOT NULL DEFAULT '' COMMENT '支付状态原因',
  `pay_time` datetime DEFAULT NULL COMMENT '支付状态时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(100) NOT NULL COMMENT '修改人',
  `update_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '修改人名字',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(100) NOT NULL COMMENT '创建人',
  `create_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '创建人名字',
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除状态,0未删除,1已删除',
  `trace_id` varchar(100) NOT NULL COMMENT 'traceId',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `bf_offline_payment_form_advance_back_detail_corp_id_IDX` (`corp_id`,`payment_form_id`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='线下业务-付款单-垫款退回-明细';

CREATE TABLE `bf_offline_payment_form_auditor` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `corp_id` bigint(20) unsigned NOT NULL COMMENT '企业ID',
  `payment_form_id` bigint(20) unsigned NOT NULL COMMENT '付款单ID',
  `payment_form_no` varchar(100) NOT NULL COMMENT '付款单编号',
  `audit_no` varchar(100) NOT NULL DEFAULT '' COMMENT '审批单号',
  `audit_by_id` bigint(20) unsigned NOT NULL COMMENT '当前审批人ID',
  `audit_by` varchar(100) NOT NULL COMMENT '当前审批人',
  `audit_by_account` varchar(100) NOT NULL COMMENT '当前审批人账号',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(100) NOT NULL COMMENT '修改人',
  `update_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '修改人名字',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(100) NOT NULL COMMENT '创建人',
  `create_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '创建人名字',
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除状态,0未删除,1已删除',
  `trace_id` varchar(100) NOT NULL COMMENT 'traceId',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `bf_offline_payment_form_auditor_corp_id_IDX` (`corp_id`,`payment_form_id`),
  KEY `bf_offline_order_corp_id_IDX` (`corp_id`,`payment_form_no`)
) ENGINE=InnoDB AUTO_INCREMENT=1725 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='线下业务-付款单-审批单的当前审批人';

CREATE TABLE `bf_offline_payment_form_public_order` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `corp_id` bigint(20) unsigned NOT NULL COMMENT '企业ID',
  `payment_form_id` bigint(20) unsigned NOT NULL COMMENT '付款单ID',
  `form_pay_type` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '付款单支付方式,1普通支付,2被负冲,3负冲',
  `order_type` tinyint(3) unsigned NOT NULL COMMENT '订单类型,1正常订单,2退款订单',
  `order_child_parent_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '子订单的父亲订单ID',
  `order_child_parent_no` varchar(100) NOT NULL DEFAULT '' COMMENT '子订单的父子订单号',
  `order_child_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '子订单ID',
  `order_child_no` varchar(100) NOT NULL DEFAULT '' COMMENT '子订单号',
  `project_id` bigint(20) unsigned NOT NULL COMMENT '项目ID',
  `project_name` varchar(100) NOT NULL COMMENT '项目名称',
  `customer_id` bigint(20) unsigned NOT NULL COMMENT '客户ID',
  `customer_name` varchar(100) NOT NULL COMMENT '客户名称',
  `expenses_parent_id` bigint(20) unsigned NOT NULL COMMENT '费用大类ID',
  `expenses_parent` varchar(100) NOT NULL COMMENT '冗余费用大类名称',
  `expenses_child_id` bigint(20) unsigned NOT NULL COMMENT '费用小类ID',
  `expenses_child` varchar(100) NOT NULL COMMENT '冗余费用小类名称',
  `amount` decimal(12,2) NOT NULL COMMENT '本次付款金额',
  `pay_no` varchar(100) NOT NULL DEFAULT '' COMMENT '最新支付号',
  `pay_state` tinyint(3) unsigned NOT NULL DEFAULT '1' COMMENT '最新支付状态,1待支付,2支付中,3已支付(部分成功),4已经支付(全部成功),5已支付(全部失败),6未支付被驳回,7支付成功后被退回,8已取消',
  `pay_time` datetime DEFAULT NULL COMMENT '支付状态时间',
  `pay_state_reason` varchar(1000) NOT NULL DEFAULT '' COMMENT '支付状态原因',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(100) NOT NULL COMMENT '修改人',
  `update_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '修改人名字',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(100) NOT NULL COMMENT '创建人',
  `create_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '创建人名字',
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除状态,0未删除,1已删除',
  `trace_id` varchar(100) NOT NULL COMMENT 'traceId',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`),
  KEY `bf_offline_payment_form_public_order_corp_id_IDX` (`corp_id`,`payment_form_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1125 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='线下业务-付款单-对公付款-明细';

CREATE TABLE `bf_offline_payment_form_pay_detail` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `corp_id` bigint(20) unsigned NOT NULL COMMENT '企业ID',
  `payment_form_id` bigint(20) unsigned NOT NULL COMMENT '付款单ID',
  `payment_form_no` varchar(100) NOT NULL COMMENT '付款单号',
  `pay_no` varchar(100) DEFAULT NULL COMMENT '支付单号',
  `detail_type` tinyint(3) unsigned NOT NULL COMMENT '记录类型,1申请支付,2被退回,3被负冲-负冲',
  `data_json` json DEFAULT NULL COMMENT '数据json格式',
  `data_json_version` int(10) unsigned NOT NULL DEFAULT '1' COMMENT '数据json格式版本号',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(100) NOT NULL COMMENT '修改人',
  `update_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '修改人名字',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(100) NOT NULL COMMENT '创建人',
  `create_by_name` varchar(100) NOT NULL DEFAULT 'system' COMMENT '创建人名字',
  `is_deleted` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除状态,0未删除,1已删除',
  `trace_id` varchar(100) NOT NULL COMMENT 'traceId',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '乐观锁版本号',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1021 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='线下业务-付款单-付款记录';
